### ISSUE TITLE
Pretrain data used during retrain

### ISSUE THREAD

**Issue by yu868** [Arnav0400/ViT-Slim#1]
Dear author: I am very interested in your article and have studied it carefully for some time. Now I would like to try to reproduce your retrain process and results first. I wonder if you could publish the pretrain data needed in the retrain process, that is, the parameter --pretrained_path required. I would appreciate it if you could share!!

**Comment by Arnav0400** [comment]
--pretrained_path is actually the pretrained model weights which are available here - https://github.com/facebookresearch/deit/blob/main/README_deit.md#model-zoo
