### ISSUE TITLE
Result about fine-grained few-shot dataset

### ISSUE THREAD

**Issue by huangfuyb** [Arnav0400/ViT-Slim#14]
Hi, nice job. Could you please provide me with the exact numbers of **Figure 2: Results on few-shot learning datasets**? I want to  compare with my method. Thanks.

**Comment by Arnav0400** [comment]
|    --   | Food101 | StanfordCars | Flowers102 | FGVCAircraft | OxfordPets |
|:-------:|:-------:|:------------:|:----------:|:------------:|:----------:|
|  GLoRA  |    36   |      7.8     |    88.7    |      8.7     |    72.6    |
|         |   54.8  |     16.5     |    97.4    |     14.4     |    77.3    |
|         |   65.1  |     30.8     |    99.1    |      24      |    89.1    |
|         |   71.3  |      55      |    99.3    |      38      |    90.1    |
|         |   75.9  |     74.3     |    99.6    |     54.1     |    91.4    |
|   NOAH  |   31.8  |      7.3     |    88.1    |      8.2     |    69.7    |
|         |   51.6  |     13.2     |    96.9    |     13.5     |    78.1    |
|         |   63.8  |     25.5     |    98.1    |     23.1     |    84.9    |
|         | 71.5    | 46.2         | 99.4       | 34           | 88         |
|         | 76.3    | 68.6         | 99.5       | 49.1         | 89         |
| VPT     | 23.5    | 5.5          | 58.8       | 6.4          | 56.8       |
|         | 46.7    | 9.6          | 95.4       | 11.2         | 66.1       |
|         | 60.6    | 20.7         | 98         | 19           | 85.3       |
|         | 67.8    | 33.5         | 99.2       | 28.9         | 88.6       |
|         | 72.6    | 56           | 99.4       | 42.5         | 89.6       |
| Lora    | 31.8    | 6.7          | 88.5       | 9            | 68.6       |
|         | 48.7    | 13.5         | 96.4       | 13.5         | 76.1       |
|         | 59      | 26.4         | 98.1       | 22.1         | 85.7       |
|         | 66.4    | 45.9         | 99.1       | 34.6         | 87.3       |
|         | 72.5    | 68.2         | 99.6       | 47.6         | 88.7       |
| Adapter | 31.4    | 7.5          | 88.6       | 9.1          | 68         |
|         | 49      | 13.4         | 96.3       | 13.3         | 76.3       |
|         | 59.8    | 23.7         | 98.1       | 21.1         | 85.8       |
|         | 66.8    | 39.9         | 99.2       | 32           | 88.2       |
|         | 71.7    | 60.4         | 99.5       | 45.2         | 89.1       |
