### ISSUE TITLE
--head_search,--uniform_search,self.is_searched

### ISSUE THREAD

**Issue by yu868** [Arnav0400/ViT-Slim#3]
Hello, I have studied the code for a period of time, from some questions to ask.
First, what does self.is_searched = False, as defined in the SparseMlp class and the Class SparseAttention class, mean and do? When is self.is_searchable set to true?
What do --head_search and --uniform_search in the argparse mean? Under what circumstances are they used and set them to true?
I'm really sorry that my level is not high , after studying the article and code, I have questions about the above problems for a long time. I would be very, very grateful if you could take some time to answer. Thank you very much
![image](https://user-images.githubusercontent.com/93248375/174713673-6b9fd8bc-b21b-49e1-85b8-03aafc57a36e.png)
![image](https://user-images.githubusercontent.com/93248375/174713774-81972829-287e-498b-b371-17adfb385ed2.png)

**Comment by Arnav0400** [comment]
self.is_searched is a boolean flag indicating if the search phase is complete or not. While re-training the searched model, self.is_searched is set to be true, the script handles this no need to manually tune it.
--head_search and --uniform_search are two boolean flags to perform complete head pruning and uniform attention head dimension search respectively. You can ignore these flags as they give inferior results.
