### ISSUE TITLE
Is it possible to deploy the pruned model for inference speedup ?

### ISSUE THREAD

**Issue by reversal67** [Arnav0400/ViT-Slim#4]
Dear author: Since there's only FLOPS reduction reported in the paper, I am curious to know if it's possible to convert the pruned model to ONNX for inference speedup on hardware. Thanks

**Comment by Arnav0400** [comment]
Hey you can find the attached code for getting a pruned model. the branch is - throughput
[ViT-Slim-throughput.zip](https://github.com/Arnav0400/ViT-Slim/files/9026741/ViT-Slimming-throughput.zip)
